### ISSUE TITLE
Password generated randomly prevents usage of mobile app

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/wallabag_ynh#14]
The Wallabag web app is currently configured to log in without a password from the home menu; however, it's impossible to enter with the user's name and password. The Android application is able to work with just the feed token, to which the user has access, but in read-only mode. Any write access (uploading URLs, marking items as read) requires the user and password, and the latter is literally generated at random (see hooks/post_user_create).

**Comment by jeromelebleu** [comment]
Thanks for your report, I've updated the [README](https://github.com/YunoHost-Apps/wallabag_ynh#limitation) accordingly. Unfortunately, there is no other solution than implementing the LDAP support for users authentication... As the v2 is out, I'll not spend some time to do that, but I'll try to do it for this new version in the hope that it will be easier thanks to Symfony... But, if you want to do it - or someone else - and/or need some help, feel free to do/ask!
