### ISSUE TITLE
PLease update to 2.0

### ISSUE THREAD

**Issue by Kamaluk** [YunoHost-Apps/wallabag_ynh#17]
The 2.0 Version is out
http://doc.wallabag.org/en/master/

**Comment by M5oul** [comment]
Work in progress: https://github.com/YunoHost-Apps/wallabag2_ynh

**Comment by Kamaluk** [comment]
ah, sorry! :+1:

**Comment by M5oul** [comment]
A link must be added in the readme.

**Comment by lapineige** [comment]
@M5oul  did a PR #18 for that

**Comment by lapineige** [comment]
Maybe we should add it to the testing branch too ?
Or is it a branch that will disappear ?
